openapi: 3.0.3
info:
  title: API de gestion des transactions pour la Phase 2
  description: Document décrivant les API proposées pour les transactions pour la Phase 2 de l'application web
  version: 2.0.0
servers:
  - url: http://localhost:3001

paths:
  /transactions:
    get:
      summary: Récupérer les transactions du mois en cours
      description: Récupère toutes les transactions pour le mois en cours, groupées par compte
      responses:
        "200":
          description: Succès de la récupération des transactions
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionList"
        "404":
          description: Aucune transaction n'a été trouvée pour le mois en cours
        "500":
          description: Erreur serveur

  /transactions/{transactionId}:
    get:
      summary: Récupérer les détails d'une transaction spécifique
      description: Récupère les détails d'une transaction spécifique en fonction de l'ID de transaction fourni
      parameters:
        - in: path
          name: transactionId
          required: true
          description: ID de la transaction à récupérer
          schema:
            type: string
      responses:
        "200":
          description: Succès de la récupération des détails de la transaction
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDetails"
        "404":
          description: Transaction non trouvée
        "500":
          description: Erreur serveur

  /transactions/add:
    post:
      summary: Ajouter une nouvelle transaction
      description: Permet d'ajouter une nouvelle transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionInput"
      responses:
        "200":
          description: Transaction ajoutée avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionOutput"
        "400":
          description: Requête invalide
        "500":
          description: Erreur serveur

  /transactions/update/{transactionId}:
    put:
      summary: Mettre à jour les informations d'une transaction existante
      description: Met à jour les informations d'une transaction existante en fonction de l'ID de transaction fourni
      parameters:
        - in: path
          name: transactionId
          required: true
          description: ID de la transaction à mettre à jour
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionInput"
      responses:
        "200":
          description: Transaction mise à jour avec succès
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionOutput"
        "404":
          description: Transaction non trouvée
        "500":
          description: Erreur serveur

  /transactions/delete/{transactionId}:
    delete:
      summary: Supprimer une transaction
      description: Supprime une transaction en fonction de l'ID de transaction fourni
      parameters:
        - in: path
          name: transactionId
          required: true
          description: ID de la transaction à supprimer
          schema:
            type: string
      responses:
        "200":
          description: Transaction supprimée avec succès
        "404":
          description: Transaction non trouvée
        "500":
          description: Erreur serveur

components:
  schemas:
    TransactionList:
      type: array
      items:
        $ref: "#/components/schemas/TransactionDetails"
    TransactionDetails:
      type: object
      properties:
        transactionId:
          type: string
          description: ID de la transaction
        accountId:
          type: string
          description: ID du compte associé à la transaction
        amount:
          type: number
          description: Montant de la transaction
        description:
          type: string
          description: Description de la transaction
        date:
          type: string
          format: date
    TransactionInput:
      type: object
      properties:
        accountId:
          type: string
          description: ID du compte associé à la transaction
        amount:
          type: number
          description: Montant de la transaction
        description:
          type: string
          description: Description de la transaction
    TransactionOutput:
      type: object
      properties:
        transactionId:
          type: string
          description: ID de la transaction
        accountId:
          type: string
          description: ID du compte associé à la transaction
        amount:
          type: number
          description: Montant de la transaction
        description:
          type: string
          description: Description de la transaction
        date:
          type: string
          format: date
